import Head from 'next/head'
import Landing from './Landing/_landing'
import HomePage from './Home/_home'
import { useSelector } from 'react-redux'

export default function Home() {
  const {user} = useSelector(state => state.auth)
  return (
    <>
      <Head>
        <title>Alwise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {user ? <HomePage/> : <Landing/>}
    </>
  )
}
